### ISSUE TITLE
Calibration fails if almond_type_mapping_path is specified

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/decaNLP#236]
```
Traceback (most recent call last):
  File "/usr/local/bin/genienlp", line 33, in <module>
    sys.exit(load_entry_point('genienlp', 'console_scripts', 'genienlp')())
  File "/opt/genienlp/genienlp/__main__.py", line 108, in main
    subcommands[argv.subcommand][2](argv)
  File "/opt/genienlp/genienlp/predict.py", line 570, in main
    run(args, devices[0])
  File "/opt/genienlp/genienlp/predict.py", line 394, in run
    val_sets = prepare_data(args, src_lang)
  File "/opt/genienlp/genienlp/predict.py", line 333, in prepare_data
    ned_model = init_ned_model(args)
  File "/opt/genienlp/genienlp/ned/ned_utils.py", line 111, in init_ned_model
    ned_model = ned_class(args)
  File "/opt/genienlp/genienlp/ned/bootleg.py", line 53, in __init__
    super().__init__(args)
  File "/opt/genienlp/genienlp/ned/abstract.py", line 65, in __init__
    with open(os.path.join(self.args.root, self.args.almond_type_mapping_path)) as fin:
AttributeError: 'Namespace' object has no attribute 'root'
```

**Comment by gcampax** [comment]
Affects evaluation as well:
```
Traceback (most recent call last):
  File "/usr/local/bin/genienlp", line 33, in <module>
    sys.exit(load_entry_point('genienlp', 'console_scripts', 'genienlp')())
  File "/opt/genienlp/genienlp/__main__.py", line 108, in main
    subcommands[argv.subcommand][2](argv)
  File "/opt/genienlp/genienlp/server.py", line 378, in main
    model, device, confidence_estimators, estimator_filenames, ned_model = init(args)
  File "/opt/genienlp/genienlp/server.py", line 333, in init
    ned_model = init_ned_model(args, 'bootleg-annotator')
  File "/opt/genienlp/genienlp/ned/ned_utils.py", line 111, in init_ned_model
    ned_model = ned_class(args)
  File "/opt/genienlp/genienlp/ned/bootleg.py", line 279, in __init__
    super().__init__(args)
  File "/opt/genienlp/genienlp/ned/bootleg.py", line 53, in __init__
    super().__init__(args)
  File "/opt/genienlp/genienlp/ned/abstract.py", line 65, in __init__
    with open(os.path.join(self.args.root, self.args.almond_type_mapping_path)) as fin:
AttributeError: 'Namespace' object has no attribute 'root'
Prediction worker had an error: Worker died
```
